namespace :pubmed do
  desc "index pubmed journals"
  task :index => :environment do
    years = ENV['YEARS'] ? eval(ENV['YEARS']) : 1990..2014
    years = Range.new(years, years) if years.is_a? Integer
    raise "Year range starts too early. Choose a year after 1900." if years.first < 1900
    raise "Year range ends after the the current year." if years.last > Time.now.utc.year

    journals = [
      "Acta Psychologica",
      "Aggress Behav",
      "Adaptive Behavior",
      "Adolescence",
      "Advances in Child Development and Behavior",
      "Advances in Experimental Social Psychology",
      "Advances in the Study of Behavior",
      "American Journal of Community Psychology",
      "American Journal of Psychotherapy",
      "Am Psychol",
      "Annals of Neurology",
      "Annual Review of Psychology",
      "Aphasiology",
      "Applied Cognitive Psychology",
      "Applied Developmental Science",
      "Applied Ergonomics",
      "Applied Psychological Measurement",
      "Archives of General Psychiatry",
      "Archives of Scientific Psychology",
      "Archives of Sexual Behavior",
      "Asian Journal of Social Psychology",
      "Assessment",
      "ASN Neuro",
      "Atten Percept Psychophys",
      "Australian Journal of Psychology",
      "Basic and Applied Social Psychology",
      "Behavior Genetics",
      "Behavior Research Methods",
      "Behavior Therapy",
      "Behavioral and Brain Functions",
      "Behavioral and Brain Sciences",
      "Behavioral Neuroscience",
      "Behaviour Research and Therapy",
      "Behaviour",
      "Behavioural and Cognitive Psychotherapy",
      "Behavioural Brain Research",
      "Biological Cybernetics",
      "Biological Psychiatry",
      "Biological Psychology",
      "Biosystems",
      "BMC Neuroscience",
      "Brain",
      "Brain and Cognition",
      "Brain and Language",
      "Brain Research",
      "Brain Research Bulletin",
      "Brain Research Reviews",
      "Br J Clin Psychol",
      "Br J Dev Psychol",
      "Br J Educ Psychol",
      "Br J Health Psychol",
      "Br J Math Stat Psychol",
      "Br J Med Psychol",
      "Br J Psychiatry",
      "Br J Psychol",
      "Br J Soc Psychol",
      "British Journal of Sports Medicine",
      "Can J Behav Sci",
      "Can J Exp Psychol",
      "Can J Psychiatry",
      "Canadian Journal of Psychology",
      "Can Psychol",
      "Cereb Cortex",
      "Chemical Senses",
      "Child Abuse Negl",
      "Child Development",
      "Childhood Education",
      "Clinical Psychology Review",
      "Cognition & Emotion",
      "Cognition",
      "Cognitive Neurodynamics",
      "Cognitive Neuropsychology",
      "Cognitive Psychology",
      "Cognitive Science",
      "Cognitive Therapy and Research",
      "Consciousness and Cognition",
      "Contemporary Psychoanalysis",
      "Cortex",
      "Couns Psychol",
      "Criminal Justice and Behavior",
      "Criminology",
      "Current Alzheimer Research",
      "Current Directions in Psychological Science",
      "Current Opinion in Neurobiology",
      "Development and Psychopathology",
      "Developmental Neuropsychology",
      "Developmental Psychology",
      "Early Childhood Research Quarterly",
      "Ecol Psychol",
      "Education Policy Analysis Archives",
      "Educational and Psychological Measurement",
      "Educational Psychologist",
      "Educ Res",
      "Educational Psychology Review",
      "Emerg Adulthood",
      "Emotion",
      "European Journal of Behavior Analysis",
      "Eur J Cogn Psychol",
      "Eur J Neurosci",
      "European Journal of Personality",
      "Eur J Psychol Assess",
      "European Journal of Social Psychology",
      "European Psychologist",
      "Evol Hum Behav",
      "Exceptional Children",
      "Experimental and Clinical Psychopharmacology",
      "Experimental Brain Research",
      "Experimental Psychology",
      "Frontiers in aging neuroscience",
      "Frontiers in behavioral neuroscience",
      "Frontiers in Computational Neuroscience",
      "Frontiers in Human Neuroscience",
      "Frontiers in neuroinformatics",
      "Frontiers in psychiatry",
      "Frontiers in Psychology",
      "Frontiers in systems neuroscience",
      "Genes Brain Behav",
      "Health Psychol",
      "Hippocampus",
      "History of Psychology",
      "Human Brain Mapping",
      "Human Resource Management",
      "Industrial and Organizational Psychology",
      "Infant Behavior & Development",
      "Int J Psychol Relig",
      "Int J Aviat Psychol",
      "Int J Clin Exp Hypn",
      "Int J Dev Neurosci",
      "International Journal of Neural Systems",
      "Int J Neuropsychopharmacol",
      "Int J Neurosci",
      "Int J Psychol",
      "Int J Psychophysiol",
      "International Journal of Stress Management",
      "Int J Transgend",
      "Journal of Abnormal Child Psychology",
      "Journal of Abnormal Psychology",
      "Journal of Addictive Diseases",
      "Journal of Adolescence",
      "Journal of Applied Behavior Analysis",
      "J Appl Behav Sci",
      "J Appl Psychol",
      "Journal of Applied Research in Memory and Cognition",
      "Journal of Applied Social Psychology",
      "J Artif Intell Res",
      "Journal of Autism and Developmental Disorders",
      "J Behav Health Serv Res",
      "Journal of Behavioral Medicine",
      "J Cereb Blood Flow Metab",
      "J Child Psychol Psychiatry",
      "J Clin Psychiatry",
      "Journal of Clinical Psychology",
      "Journal of Cognitive Neuroscience",
      "Journal of College Student Development",
      "Journal of Community & Applied Social Psychology",
      "Journal of Community Psychology",
      "Journal of Comparative Psychology",
      "Journal of Computational Neuroscience",
      "J Conscious Stud",
      "Journal of Consulting and Clinical Psychology",
      "Journal of Contemporary Psychotherapy",
      "Journal of Counseling Psychology",
      "Journal of Cross-Cultural Psychology",
      "J Educ Psychol",
      "J Educ Res",
      "Journal of Experimental Child Psychology",
      "Journal of Experimental Education",
      "Journal of Experimental Psychology",
      "J Exp Psychol Anim Behav Process",
      "J Exp Psychol Anim Learn Cogn",
      "J Exp Psychol Appl",
      "J Exp Psychol Gen",
      "J Exp Psychol Hum Learn",
      "J Exp Psychol Hum Percept Perform",
      "J Exp Psychol Learn Mem Cogn",
      "Journal of Experimental Social Psychology",
      "J Fam Psychol",
      "J Genet Psychol",
      "Journal of Health and Social Behavior",
      "Journal of Health Psychology",
      "Journal of Homosexuality",
      "Journal of Integrative Neuroscience",
      "Journal of Marriage and the Family",
      "Journal of Mathematical Psychology",
      "Journal of Memory and Language",
      "J Mol Neurosci",
      "Journal of Motor Behavior",
      "Journal of Multicultural Counseling and Development",
      "J Nerv Ment Dis",
      "Journal of Neural Engineering",
      "Journal of Neurochemistry",
      "Journal of Neurogenetics",
      "Journal of Neurophysiology",
      "J Neurosci",
      "Journal of Neuroscience Research",
      "Journal of NeuroVirology",
      "Journal of Occupational and Organizational Psychology",
      "Journal of Occupational Health Psychology",
      "Journal of Organizational Behavior",
      "Journal of Personality and Social Psychology",
      "Journal of Personality",
      "Journal of Personality Assessment",
      "Journal of Personality Disorders",
      "J Psychiatry Neurosci",
      "J Psychohist",
      "Journal of Psychopathology and Behavioral Assessment",
      "J Psychopharmacol",
      "Journal of Religion and Health",
      "Journal of Research in Personality",
      "Journal of School Psychology",
      "Journal of Sex & Marital Therapy",
      "Journal of Sex Research",
      "J Soc Issues",
      "J Soc Psychol",
      "Journal of Sport & Exercise Psychology",
      "J Stat Educ",
      "Journal of the American Academy of Child and Adolescent Psychiatry",
      "Journal of the American Psychoanalytic Association",
      "Journal of the Experimental Analysis of Behavior",
      "Journal of the History of the Behavioral Sciences",
      "Journal of the History of the Neurosciences",
      "J Int Neuropsychol Soc",
      "Journal of Vision",
      "Journal of Vocational Behavior",
      "J Gerontol B Psychol Sci Soc Sci",
      "Language and Cognitive Processes",
      "Leadersh Q",
      "Learning & Behavior",
      "Learning and Individual Differences",
      "Learn Mem",
      "Learning and Motivation",
      "Memory",
      "Memory & Cognition",
      "Metaphor and Symbol",
      "Mind & Language",
      "Mind",
      "Molecular and Cellular Neurosciences",
      "Molecular Psychiatry",
      "Music Perception",
      "Nature",
      "Nature Neuroscience",
      "Nat Rev Neurosci",
      "Nebr Symp Motiv",
      "Neural Computation",
      "Neural Development",
      "Neural Netw",
      "Neural Regeneration Research",
      "Neurobiology of Learning and Memory",
      "Neurocase",
      "Neurocomputing",
      "Neurogenetics",
      "NeuroImage",
      "Neuroinformatics",
      "Neuron",
      "Neuroophthalmology",
      "Neuropharmacology",
      "Neuropsychobiology",
      "Neuropsychologia",
      "Neuropsychological Rehabilitation",
      "Neuropsychology Review",
      "Neuropsychology",
      "Neuropsychopharmacology",
      "Neuroquantology",
      "NeuroReport",
      "Neuroscience",
      "Neuroscience and Biobehavioral Reviews",
      "Neuroscience Letters",
      "Neurosurgery",
      "North American Journal of Psychology",
      "Organizational Behavior and Human Decision Processes",
      "Pastoral Psychology",
      "Perception",
      "Perception & Psychophysics",
      "Perceptual and Motor Skills",
      "Personal Relationships",
      "Personality and Individual Differences",
      "Personality & Social Psychology Bulletin",
      "Pers Soc Psychol Rev",
      "Personnel Psychology",
      "Perspect Psychol Sci",
      "Physiology & Behavior",
      "Physiology & Behavior",
      "PLoS One",
      "Proc Natl Acad Sci U S A",
      "Prof Psychol Res Pr",
      "Psyche",
      "Psychiatr Clin North Am",
      "Psychiatric Genetics",
      "Psychoanalytic Dialogues",
      "Psychoanal Psychol",
      "Psychoanal Q",
      "Psychoanalytic Review",
      "Psychoanal Study Child",
      "Psychologica Belgica",
      "Psychological Assessment",
      "Psychological Bulletin",
      "Psychological Inquiry",
      "Psychological Medicine",
      "Psychol Rec",
      "Psychological Reports",
      "Psychological Research",
      "Psychological Review",
      "Psychological Science",
      "Psychol Sci Public Interest",
      "Psychology and Aging",
      "Psychology in the Schools",
      "Psychol Addict Behav",
      "Psychol Aesthet Creat Arts",
      "Psychol Learn Motiv",
      "Psychology of Music",
      "Psychology of Women Quarterly",
      "Psychol Public Policy Law",
      "Psychometrika",
      "Psychonomic Bulletin & Review",
      "Psychopharmacology",
      "Psychophysiology",
      "Psychosomatic Medicine",
      "Psychotherapy and Psychosomatics",
      "Quality & Quantity",
      "Q J Exp Psychol",
      "Q J Exp Psychol A",
      "Q J Exp Psychol B",
      "Rev Gen Psychol",
      "Review of Philosophy and Psychology",
      "School Psychology Review",
      "Science",
      "Self Identity",
      "Sex Roles",
      "Sexuality & Culture",
      "Social and Personality Psychology Compass",
      "Social Cognition",
      "Social Indicators Research",
      "Social Neuroscience",
      "Social Problems",
      "Social Psychology Quarterly",
      "Swiss J Psychol",
      "Synapse",
      "Systems Research and Behavioral Science",
      "Teach Psychol",
      "Cerebellum",
      "The Electronic Journal of Human Sexuality",
      "The International Journal for the Psychology of Religion",
      "The Journal of Psychology",
      "Neuroscientist",
      "Qual Rep",
      "Theory & Psychology",
      "Thinking & Reasoning",
      "Traumatology",
      "Trends in Cognitive Sciences",
      "Twin Res Hum Genet",
      "Vision Research",
      "Visual Cognition",
      "Visual Neuroscience",
      "Western Criminology Review",
      "Work and Stress",
      "Youth & Society",
    ]

    if ENV['JOURNALS']
      journals = journals & ENV['JOURNALS'].split(",")
    end

    journals.each do |journal|
      years.each do |year|
        Pubmed.new(
          journal,
          year
        ).crawl
      end
    end
  end
end
