language: ruby
rvm:
- 2.0.0
env:
- DB=postgres
before_script:
- psql -c 'create database science_commons_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
addons:
  postgresql: '9.3'
services:
- elasticsearch
- redis-server
deploy:
  provider: heroku
  api_key:
    secure: NWuhDAyAPwrwHhR9LhY8lcJaQ2PnaZ/aNP4XJ8cZ9L5NCND/dgW7bCybeeq7/8yQ6TK4T5a22Ub1nj1swNzLHmy6lm+MhLcTCe367nu+6pDBaaZ0belKnk0ZUoho5VcwsqVeVrcuB8lolJjrHSQiomXtnio+TSGXyf2X28vkrKo=
  skip_cleanup: true
  app:
    master: curatescience
    staging: curatescience-staging
