octopus:
  environments:
    - production
  production:
    s1:
      adapter: postgresql
      encoding: unicode
      database: science_commons_api_production
      pool: 5
      username: science_commons_api
      password: postgresql