# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
client = Oauth2::Client.create({
  name: 'papercollab'
})

client = Oauth2::Client.create({
  name: 'www'
})

User.create!([
  {email: "your_name@gmail.com", remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, admin: true, curator: nil, name: "Your Name Here", invite_count: 100}
             ])

Invite.create!([
  {invite_id: nil, inviter_id: 1, email: "your_name@gmail.com"}
])

ArticleAuthor.create!([
  {article_id: 60045, author_id: 54, number: 0},
  {article_id: 60045, author_id: 55, number: 1},
  {article_id: 60045, author_id: 56, number: 2},
  {article_id: 60046, author_id: 57, number: 0},
  {article_id: 60046, author_id: 58, number: 1},
  {article_id: 60046, author_id: 54, number: 2},
  {article_id: 60047, author_id: 59, number: 0},
  {article_id: 60047, author_id: 54, number: 1},
  {article_id: 51037, author_id: 23, number: nil},
  {article_id: 51037, author_id: 24, number: nil},
  {article_id: 51037, author_id: 25, number: nil},
  {article_id: 51037, author_id: 26, number: nil},
  {article_id: 51037, author_id: 27, number: nil},
  {article_id: 54094, author_id: 31, number: nil},
  {article_id: 54094, author_id: 32, number: nil},
  {article_id: 48296, author_id: 35, number: nil},
  {article_id: 48296, author_id: 36, number: nil},
  {article_id: 48296, author_id: 37, number: nil},
  {article_id: 52529, author_id: 19, number: 0},
  {article_id: 52529, author_id: 20, number: 1},
  {article_id: 52529, author_id: 21, number: 2},
  {article_id: 49864, author_id: 63, number: 0},
  {article_id: 49864, author_id: 64, number: 1},
  {article_id: 59297, author_id: 5, number: 0},
  {article_id: 59297, author_id: 6, number: 1},
  {article_id: 59309, author_id: 39, number: 0},
  {article_id: 56241, author_id: 40, number: 0},
  {article_id: 56241, author_id: 41, number: 1},
  {article_id: 60035, author_id: 5, number: 0},
  {article_id: 60035, author_id: 42, number: 1},
  {article_id: 60036, author_id: 43, number: 0},
  {article_id: 60039, author_id: 5, number: 0},
  {article_id: 60039, author_id: 14, number: 1},
  {article_id: 60040, author_id: 45, number: 0},
  {article_id: 60040, author_id: 46, number: 1},
  {article_id: 60040, author_id: 47, number: 2},
  {article_id: 60041, author_id: 48, number: 0},
  {article_id: 60041, author_id: 49, number: 1},
  {article_id: 60041, author_id: 50, number: 2},
  {article_id: 60041, author_id: 51, number: 3},
  {article_id: 60042, author_id: 7, number: 0},
  {article_id: 60042, author_id: 52, number: 1},
  {article_id: 60042, author_id: 53, number: 2},
  {article_id: 93543, author_id: 69, number: 0},
  {article_id: 93543, author_id: 70, number: 1},
  {article_id: 93543, author_id: 71, number: 2},
  {article_id: 93543, author_id: 72, number: 3},
  {article_id: 93544, author_id: 7, number: 0},
  {article_id: 93544, author_id: 73, number: 1},
  {article_id: 93544, author_id: 52, number: 2},
  {article_id: 93548, author_id: 45, number: 0},
  {article_id: 93548, author_id: 75, number: 1},
  {article_id: 93548, author_id: 76, number: 2},
  {article_id: 93548, author_id: 77, number: 3},
  {article_id: 93548, author_id: 78, number: 4},
  {article_id: 93549, author_id: 52, number: 0},
  {article_id: 93549, author_id: 53, number: 1},
  {article_id: 93549, author_id: 73, number: 2},
  {article_id: 93549, author_id: 7, number: 3},
  {article_id: 53406, author_id: 83, number: 0},
  {article_id: 53406, author_id: 84, number: 1},
  {article_id: 53406, author_id: 85, number: 2},
  {article_id: 53406, author_id: 86, number: 3},
  {article_id: 93552, author_id: 87, number: 0},
  {article_id: 93552, author_id: 88, number: 1},
  {article_id: 93552, author_id: 89, number: 2},
  {article_id: 93553, author_id: 90, number: 0},
  {article_id: 93553, author_id: 91, number: 1},
  {article_id: 93553, author_id: 92, number: 2},
  {article_id: 93554, author_id: 90, number: 0},
  {article_id: 335169, author_id: 56, number: 0},
  {article_id: 335169, author_id: 123, number: 1},
  {article_id: 335169, author_id: 124, number: 2},
  {article_id: 335170, author_id: 7, number: 0},
  {article_id: 335170, author_id: 52, number: 1},
  {article_id: 93555, author_id: 93, number: 0},
  {article_id: 93555, author_id: 94, number: 1},
  {article_id: 93555, author_id: 95, number: 2},
  {article_id: 93555, author_id: 96, number: 3},
  {article_id: 93556, author_id: 97, number: 0},
  {article_id: 93556, author_id: 98, number: 1},
  {article_id: 93556, author_id: 99, number: 2},
  {article_id: 93558, author_id: 104, number: 0},
  {article_id: 93558, author_id: 103, number: 1},
  {article_id: 93558, author_id: 105, number: 2},
  {article_id: 93558, author_id: 102, number: 3},
  {article_id: 93558, author_id: 106, number: 4},
  {article_id: 93558, author_id: 107, number: 5},
  {article_id: 93557, author_id: 100, number: 0},
  {article_id: 93557, author_id: 101, number: 1},
  {article_id: 93557, author_id: 102, number: 2},
  {article_id: 93557, author_id: 103, number: 3},
  {article_id: 93561, author_id: 117, number: 0},
  {article_id: 93561, author_id: 118, number: 1},
  {article_id: 93562, author_id: 119, number: 0}
])
Author.create!([
  {first_name: "Piam", middle_name: "", last_name: "Kiarostami", orcid: "", job_title: "Roommate", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Christine", middle_name: "", last_name: "Madurski", orcid: "", job_title: "Graduate Student", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Harry", middle_name: "", last_name: "Reis", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Christopher", middle_name: "J", last_name: "Wilbur", orcid: "", job_title: "Assistant Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Etienne", middle_name: "P.", last_name: "LeBel", orcid: "", job_title: "Scientific Curator", user_id: nil, same_as_id: nil, affiliations: ["University of Western Ontario", "Curate Science"], owner_id: 4},
  {first_name: "Anique", middle_name: "J", last_name: "Bourgoin", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Ben", middle_name: "", last_name: "Bowles", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 8},
  {first_name: "Linda", middle_name: "R", last_name: "Wheeldon", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Mark", middle_name: "C", last_name: "Smith", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Ian", middle_name: "A", last_name: "Apperly", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Maria", middle_name: "", last_name: "Bulgheroni", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Tomaso", middle_name: "", last_name: "Scaravilli", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Roberto", middle_name: "", last_name: "Tirindelli", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Umberto", middle_name: "", last_name: "Castiello", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Valentina", middle_name: "", last_name: "Parma", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Corbin", middle_name: "A", last_name: "Cunningham", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Jeremy", middle_name: "M", last_name: "Wolfe", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Hackjin", middle_name: "", last_name: "Kim", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Hackjin", middle_name: "", last_name: "Kim", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Shinsuke", middle_name: "", last_name: "Shimojo", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "John", middle_name: "P", last_name: "O'Doherty", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 3},
  {first_name: "Joshua", middle_name: "", last_name: "Correll", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Anna", middle_name: "C", last_name: "Nobre", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Mark", middle_name: "G", last_name: "Stokes", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Lorne", middle_name: "", last_name: "Campbell", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["University of Western Ontario"], owner_id: 4},
  {first_name: "Matthew", middle_name: "", last_name: "Vess", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "John", middle_name: "A", last_name: "Bargh", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Mark", middle_name: "", last_name: "Chen", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Lara", middle_name: "", last_name: "Burrows", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Stephane", middle_name: "", last_name: "Doyen", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Olivier", middle_name: "", last_name: "Klein", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Cora-Lise", middle_name: "", last_name: "Pichon", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Axel", middle_name: "", last_name: "Cleeremans", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "N", middle_name: "", last_name: "Coburn", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Melissa", middle_name: "", last_name: "McDonald", orcid: "", job_title: "Post-doc", user_id: nil, same_as_id: nil, affiliations: ["McGill University"], owner_id: 4},
  {first_name: "Brent", middle_name: "", last_name: "Donnellan", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["Texas A&M"], owner_id: 4},
  {first_name: "Sampo", middle_name: "", last_name: "Paunonen", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Jason", middle_name: "D", last_name: "Ferrell", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: [""], owner_id: 4},
  {first_name: "Samuel", middle_name: "D", last_name: "Gosling", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["U T Austin"], owner_id: 4},
  {first_name: "Tony", middle_name: "", last_name: "Vernon", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["Western University"], owner_id: 4},
  {first_name: "X", middle_name: "", last_name: "Zhou", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: ["Western University"], owner_id: 4},
  {first_name: "T", middle_name: "", last_name: "Wildschut", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: ["Western University"], owner_id: 4},
  {first_name: "Christian", middle_name: "", last_name: "Battista", orcid: "", job_title: "Renaissance Man ", user_id: nil, same_as_id: 38, affiliations: ["", ""], owner_id: 3},
  {first_name: "K.", middle_name: "A.", last_name: "Rasinski", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "P.", middle_name: "S.", last_name: "Visser", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "M.", middle_name: "", last_name: "Zagatsky", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "E.", middle_name: "M.", last_name: "Rickett", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Doug", middle_name: "", last_name: "Rohrer", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["University of South Florida"], owner_id: 4},
  {first_name: "Hal", middle_name: "R.", last_name: "Pashler", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["UC San Diego"], owner_id: 4},
  {first_name: "Christine", middle_name: "R.", last_name: "Harris", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["UC San Diego"], owner_id: 4},
  {first_name: "Stephen", middle_name: "V", last_name: "Demjanenko\n", orcid: nil, job_title: "Coder\nRelentess Technological Badass\n\n", user_id: nil, same_as_id: nil, affiliations: ["Cisco", "Meraki", "CurateScience"], owner_id: nil},
  {first_name: "Annette", middle_name: "", last_name: "Lee-Chai", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Kimberly", middle_name: "", last_name: "Barndollar", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Peter", middle_name: "M.", last_name: "Gollwitzer", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Roman", middle_name: "", last_name: "Trotschel", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Michael", middle_name: "L", last_name: "Slepian", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "E", middle_name: "J", last_name: "Masicampo", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Negin", middle_name: "R", last_name: "Toosi", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Nalini", middle_name: "", last_name: "Ambady", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Michael", middle_name: "L", last_name: "Slepian", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "E", middle_name: "J", last_name: "Masicampo", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Negin", middle_name: "R", last_name: "Toosi", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Nalini", middle_name: "", last_name: "Ambady", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Hannah", middle_name: "", last_name: "Perfecto", orcid: "", job_title: "Grad student", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Alice", middle_name: "", last_name: "Moon", orcid: "", job_title: "Grad student", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Leif", middle_name: "", last_name: "Nelson", orcid: "", job_title: "Associate Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "N", middle_name: "B", last_name: "Jostmann", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Daniel", middle_name: "", last_name: "Lakens", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "T", middle_name: "W", last_name: "Schubert", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Rebecca", middle_name: "", last_name: "Hadley", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Chloe", middle_name: "", last_name: "Ring", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Morrisa", middle_name: "", last_name: "Gold", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Kimberly", middle_name: "", last_name: "Daubman", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Francesca", middle_name: "", last_name: "Citron", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Michael", middle_name: "", last_name: "Kucharski", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Adele", middle_name: "", last_name: "Goldberg", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Zoe", middle_name: "", last_name: "Samara", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Bernet", middle_name: "M", last_name: "Elzinga", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Heleen", middle_name: "A", last_name: "Slagter", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Sander", middle_name: "", last_name: "Nieuwenhuis", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Dora", middle_name: "", last_name: "Matzke", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Hedderik", middle_name: "", last_name: "van Rijn", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Maurits", middle_name: "W", last_name: "van der Molen", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "E-J", middle_name: "", last_name: "Wagenmakers", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Amos", middle_name: "", last_name: "Tversky", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Daniel", middle_name: "", last_name: "Kahneman", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Richard", middle_name: "A", last_name: "Klein", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Kate", middle_name: "A", last_name: "Ratliff", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Michelangelo", middle_name: "", last_name: "Vianello", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Mark", middle_name: "J", last_name: "Brandt", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Fred", middle_name: "", last_name: "Hasselman", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Hans", middle_name: "", last_name: "IJzerman", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Brian", middle_name: "A", last_name: "Nosek", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "C", middle_name: "Nathan", last_name: "DeWall", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Brad", middle_name: "J", last_name: "Bushman", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Randy", middle_name: "J", last_name: "McCarthy", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "Joe", middle_name: "", last_name: "Cesario", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["Michigan State University"], owner_id: 4},
  {first_name: "Richard", middle_name: "E", last_name: "Lucas", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: ["Michigan State University"], owner_id: 4},
  {first_name: "Darryl", middle_name: "", last_name: "Bem", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 2},
  {first_name: "Darryl", middle_name: "", last_name: "Bem", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 2},
  {first_name: "Lang", middle_name: "", last_name: "Chen", orcid: "", job_title: "Postdoc Scholar", user_id: nil, same_as_id: nil, affiliations: ["Stanford University"], owner_id: 12},
  {first_name: "Jason", middle_name: "E.", last_name: "Plaks", orcid: "", job_title: "", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4},
  {first_name: "E.", middle_name: "Tory", last_name: "Higgins", orcid: "", job_title: "Professor", user_id: nil, same_as_id: nil, affiliations: nil, owner_id: 4}
])
Comment.create!([
  {commentable_id: 200, commentable_type: "Study", comment: "Variables are blank", field: "independent_variables", owner_id: 11, comment_count: 0, anonymous: false, primary_commentable_id: 200, primary_commentable_type: "Study"},
  {commentable_id: 52529, commentable_type: "Article", comment: "foobar", field: nil, owner_id: 3, comment_count: 0, anonymous: false, primary_commentable_id: 52529, primary_commentable_type: "Article"},
  {commentable_id: 133, commentable_type: "Study", comment: "But this \"unsuccessful\" replication is unsurprising (and should be ignored) because Doyen et al. called their participants' attention to how they were supposed to walk down \nthe hallway leaving the experiment (\"Participants were clearly directed to the end of the corridor to avoid any wandering\", p. 2). We've long known that conscious attention directed to the automatic process under study can interfere with the manifestation of those automatic processes (Posner & Snyder, 1975; Neely, 1977).", field: "effect_size", owner_id: 15, comment_count: 0, anonymous: false, primary_commentable_id: 133, primary_commentable_type: "Study"},
  {commentable_id: 60040, commentable_type: "Article", comment: "But Doyen et al.'s (2012, Study 1) \"unsuccessful\" replication is unsurprising (and should be ignored) because they called their participants' attention to how they were supposed to walk down the hallway leaving the experiment (\"Participants were clearly directed to the end of the corridor to avoid any wandering\", p. 2). We've long known that conscious attention directed to the automatic process under study can interfere with the manifestation of those automatic processes (Posner & Snyder, 1975; Neely, 1977).", field: nil, owner_id: 15, comment_count: 0, anonymous: false, primary_commentable_id: 60040, primary_commentable_type: "Article"},
  {commentable_id: 212, commentable_type: "Study", comment: "test comment", field: "effect_size", owner_id: 4, comment_count: 0, anonymous: false, primary_commentable_id: 212, primary_commentable_type: "Study"},
  {commentable_id: 35, commentable_type: "Link", comment: "But when I run this syntax, it yields an overall effect size estimate whose confidence interval (CI) overlaps with Correll's (2008) original effect size CI.", field: nil, owner_id: 4, comment_count: 0, anonymous: false, primary_commentable_id: 35, primary_commentable_type: "Link"},
  {commentable_id: 129, commentable_type: "Study", comment: "This is a massive priming effect, given the nature of the prime exposure and DV", field: "effect_size", owner_id: 4, comment_count: 0, anonymous: false, primary_commentable_id: 129, primary_commentable_type: "Study"},
  {commentable_id: 135, commentable_type: "Study", comment: "99% power to detect an effect size as large (or larger) than Bargh et al.' (1996, Study 2a) d = 1.08", field: "power", owner_id: 4, comment_count: 0, anonymous: false, primary_commentable_id: 135, primary_commentable_type: "Study"},
  {commentable_id: 73, commentable_type: "Link", comment: "The following syntax successfully reproduces Donnellan et al.'s (2014) Study 1 reported correlation of r=- .06 (p>.37) from their publicly posted data. Hence, I endorse their result as reproducible.", field: nil, owner_id: 4, comment_count: 0, anonymous: false, primary_commentable_id: 73, primary_commentable_type: "Link"},
  {commentable_id: 83519, commentable_type: "Article", comment: "This paper has apparently been withdrawn.", field: nil, owner_id: 2, comment_count: 0, anonymous: false, primary_commentable_id: 83519, primary_commentable_type: "Article"}
])
FeedbackMessage.create!([
  {user_id: 3, message: "Woot first wish!", commentable_id: nil, commentable_type: nil, details: {"url"=>"/articles/93544"}},
  {user_id: 3, message: "Another wish", commentable_id: nil, commentable_type: nil, details: {"url"=>"http://localhost:8000/?#/"}},
  {user_id: 3, message: "woohoo on the test site", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta?test_js=1#/"}},
  {user_id: 3, message: "I wish this page was styled better.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta?test_js=1#/admin"}},
  {user_id: 3, message: "Fix the feedback button placement on iPad.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/admin"}},
  {user_id: 3, message: "This should go out to everyone", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/"}},
  {user_id: 3, message: "shayan thinks this is cool", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/articles/60040"}},
  {user_id: 2, message: "Feedback from Dr. Tanya Evans, Postdoctoral Fellow, Stanford Cognitive and Systems Neuroscience Lab\n\nI usually search by authors.  When I searched by the first and last authors names (menon v qin s) from a recently published nature neuroscience paper (9/14), the search did not find the article.  I had to first add the publication year to my search terms (menon v qin s 2014) in order to find it.\n\nWhen created an article it was unclear how the authors got added.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta/#/articles/188988"}},
  {user_id: 12, message: "Hey, when I tried to put info in IV row in Column 1, it got registered into column 2.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/articles/58235"}},
  {user_id: 12, message: "First and last authors in the list are really important so they should show up in the searching results.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/query/Vinod%20Menon"}},
  {user_id: 12, message: "When I tried to add an author, the blanks are not in equal size which is weird", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/authors/new"}},
  {user_id: 12, message: "When I find a paper and want to add some info to the author, it will be great if I can search from authors existing in the database or get some suggestions.", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/articles/102151"}},
  {user_id: 3, message: "Hey this is cool", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta/#/articles/60040"}},
  {user_id: 3, message: "Boo", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta/#/articles/62641"}},
  {user_id: 3, message: "hey i want it now", commentable_id: nil, commentable_type: nil, details: {"url"=>"https://www.curatescience.org/beta#/bookmarks"}}
])
Link.create!([
  {study_id: 80, name: "Rabbit", url: "rabbit", type: "data", comment_count: 0},
  {study_id: 81, name: "Data1.sav", url: "http://figshare.com/Data1.sav", type: "data", comment_count: 0},
  {study_id: 81, name: "Materials", url: "http://files.figshare.com/1409028/NLT_INPUT_forFigshare.sav", type: "materials", comment_count: 0},
  {study_id: 81, name: "Suppl_Data1.sav", url: "http://", type: "data", comment_count: 0},
  {study_id: 83, name: "Google.docx", url: "google.com", type: "data", comment_count: 0},
  {study_id: 83, name: "Yahoo.docx", url: "yahoo.com", type: "data", comment_count: 0},
  {study_id: 83, name: "Cisco.docx", url: "cisco.com", type: "materials", comment_count: 0},
  {study_id: 28, name: "google", url: "google.com", type: "data", comment_count: 0},
  {study_id: nil, name: "Data1.sav", url: "https://osf.io/qsnvb/osffiles/resultsReplication1_deIdentified.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: nil, name: "Data1.sav", url: "https://osf.io/qsnvb/osffiles/resultsReplication1_deIdentified.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 53, name: "Data1.sav", url: "https://osf.io/qsnvb/osffiles/resultsReplication1_deIdentified.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 88, name: "Data1.sav", url: "https://osf.io/qsnvb/osffiles/resultsReplication1_deIdentified.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: nil, name: "correll-replication1-data.sav", url: "https://osf.io/zx4ia/osffiles/correll-replication1-data.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 106, name: "Data", url: "https://osf.io/zx4ia/osffiles/correll-replication1-data.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 108, name: "data", url: "figshare.com", type: "data", comment_count: 0},
  {study_id: 109, name: "materials", url: "osf.io", type: "materials", comment_count: 0},
  {study_id: 112, name: "data2", url: "figshare.com2", type: "data", comment_count: 0},
  {study_id: 107, name: "data2", url: "figshare.com2", type: "data", comment_count: 0},
  {study_id: 113, name: "data2", url: "figshare.com2", type: "data", comment_count: 0},
  {study_id: 114, name: "data", url: "figshare.com", type: "data", comment_count: 0},
  {study_id: nil, name: "materials", url: "osf.io", type: "materials", comment_count: 0},
  {study_id: 115, name: "materials", url: "osf.io", type: "materials", comment_count: 0},
  {study_id: 58, name: "Data1.sav", url: "https://osf.io/w6kv5/", type: "data", comment_count: 0},
  {study_id: 58, name: "MainSyntax.sps", url: "osf.io", type: "data", comment_count: 0},
  {study_id: 79, name: "correll-replication2-data.sav", url: "https://osf.io/qe975/osffiles/correll-replication2-data.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 79, name: "wit_agg_forSAS_import2.csv", url: "https://osf.io/qe975/osffiles/wit_agg_forSAS_import2.csv/version/1/download/", type: "data", comment_count: 0},
  {study_id: 79, name: "sas_code_FFT.sas", url: "https://osf.io/qe975/osffiles/sas_code_FFT.sas/version/1/download/", type: "data", comment_count: 0},
  {study_id: 79, name: "effect-size-CIs.R", url: "https://osf.io/qe975/osffiles/effect-size-CIs.R/version/1/download/", type: "data", comment_count: 0},
  {study_id: 79, name: "mainSyntax.sps", url: "https://osf.io/qe975/osffiles/mainSyntax.sps/version/1/download/", type: "data", comment_count: 0},
  {study_id: 79, name: "ReplicationProtocol2_Correll2008_byLeBel.doc", url: "https://osf.io/czbzg/osffiles/ReplicationProtocol2_Correll2008_byLeBel.doc/version/1/download/", type: "registration", comment_count: 0},
  {study_id: nil, name: "test", url: "test", type: "data", comment_count: 0},
  {study_id: nil, name: "test", url: "test", type: "data", comment_count: 0},
  {study_id: nil, name: "test", url: "test", type: "data", comment_count: 0},
  {study_id: 137, name: "test", url: "test", type: "data", comment_count: 0},
  {study_id: nil, name: "google3", url: "google.com", type: "data", comment_count: 0},
  {study_id: nil, name: "google4", url: "google.com", type: "data", comment_count: 0},
  {study_id: nil, name: "google3", url: "google.com", type: "data", comment_count: 0},
  {study_id: nil, name: "data", url: "figshare.com", type: "data", comment_count: 0},
  {study_id: nil, name: "data3", url: "figshare.com//", type: "data", comment_count: 0},
  {study_id: nil, name: "test2", url: "figshare.com/", type: "data", comment_count: 0},
  {study_id: 160, name: "data", url: "osf.io", type: "data", comment_count: 0},
  {study_id: 99, name: "correll-replication1-data.sav", url: "https://osf.io/zx4ia/osffiles/correll-replication1-data.sav/version/1/download/", type: "data", comment_count: 0},
  {study_id: 99, name: "mainSyntax.sps", url: "https://osf.io/zx4ia/osffiles/mainSyntax.sps/version/1/download/", type: "data", comment_count: 0},
  {study_id: 99, name: "StudyMaterials_OSF.zip", url: "https://osf.io/kgedj/osffiles/StudyMaterials_OSF.zip/version/1/download/", type: "materials", comment_count: 0},
  {study_id: 99, name: "Pre-registrationProtocol.doc", url: "https://osf.io/v3hfb/osffiles/ReplicationReport_incl_Methods_Correll2008_byLeBel_final.doc/version/1/download/", type: "registration", comment_count: 0},
  {study_id: 79, name: "materials-rep2.zip", url: "https://osf.io/y5wkn/osffiles/materials-rep2.zip/version/1/download/", type: "materials", comment_count: 0},
  {study_id: 79, name: "evaluating-replication-results.R", url: "https://osf.io/qe975/osffiles/evaluating-replication-results.R/version/1/download/", type: "data", comment_count: 1},
  {study_id: nil, name: "Google", url: "Google.com", type: "data", comment_count: 2},
  {study_id: 140, name: "google", url: "google.com", type: "data", comment_count: 0},
  {study_id: 178, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 178, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 179, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 179, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 180, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 180, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 182, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 182, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 185, name: "data", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 185, name: "data2", url: "osf.io", type: "materials", comment_count: 0},
  {study_id: 186, name: "data", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 181, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 181, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 183, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 183, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 176, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 176, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 175, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: 177, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 0},
  {study_id: 177, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "materials", comment_count: 0},
  {study_id: nil, name: "Data2", url: "figshare.com2", type: "data", comment_count: 0},
  {study_id: nil, name: "google2", url: "google.com2", type: "data", comment_count: 0},
  {study_id: 183, name: "Study1_verification.SPS", url: "http://files.figshare.com/1804960/Study1_verification.SPS", type: "data", comment_count: 1},
  {study_id: 195, name: "test", url: "osf.io", type: "data", comment_count: 0},
  {study_id: 196, name: "data", url: "osf.io", type: "data", comment_count: 0},
  {study_id: 215, name: "Materials", url: "http://psychfiledrawer.org/files/8531391990603Materials.pdf", type: "materials", comment_count: 0},
  {study_id: 226, name: "data_eye_movements.csv", url: "https://osf.io/project/pxt3m/node/zzkpx/osfstorage/files/data_eye_movements.csv/?action=download&version=1", type: "data", comment_count: 0},
  {study_id: 226, name: "data_priming.csv", url: "https://osf.io/project/pxt3m/node/zzkpx/osfstorage/files/data_priming.csv/?action=download&version=1", type: "data", comment_count: 0},
  {study_id: 226, name: "Materials", url: "https://osf.io/pxt3m/", type: "materials", comment_count: 0},
  {study_id: 226, name: "Contract_AdversarialCollaboration_Final.doc", url: "https://osf.io/project/pxt3m/node/v4egi/osfstorage/files/Contract_AdversarialCollaboration_Final.doc/?action=download&version=1", type: "registration", comment_count: 0},
  {study_id: 230, name: "Pre-specified_hypotheses_and_planned_analyses.docx", url: "https://osf.io/project/d2epg/node/iwbhu/osfstorage/files/Pre-specified_hypotheses_and_planned_analyses.docx/?action=download&version=1", type: "registration", comment_count: 0},
  {study_id: 231, name: "Registered protocol", url: "https://osf.io/pm7ac/", type: "registration", comment_count: 0},
  {study_id: 231, name: "Heat_Priming_Replication-Study_2.sav", url: "https://osf.io/project/xszk6/node/pm7ac/osfstorage/files/Heat_Priming_Replication-Study_2.sav/?action=download&version=1", type: "data", comment_count: 0},
  {study_id: 231, name: "Materials", url: "https://osf.io/46utf/", type: "materials", comment_count: 0},
  {study_id: 230, name: "Het-Priming_Replication_Study_1.sav", url: "https://osf.io/project/xszk6/node/46utf/osfstorage/files/Het-Priming_Replication_Study_1.sav/?action=download&version=1", type: "data", comment_count: 0},
  {study_id: 230, name: "Materials", url: "https://osf.io/46utf/", type: "materials", comment_count: 0},
  {study_id: 235, name: "google", url: "google.com", type: "data", comment_count: 0},
  {study_id: 175, name: "Data&Materials", url: "https://www.msu.edu/~cesario/publications/publication_materials/Donnellan%20Lucas%20Cesario%20IN%20PRESS%20EMOTION%20data%20and%20materials.zip", type: "data", comment_count: 1},
  {study_id: 240, name: "Stimulus Creation Scripts", url: "https://github.com/cbattista/OpenPsyc/tree/master/stimCreators", type: "materials", comment_count: 0}
])
Replication.create!([
  {study_id: 48, replicating_study_id: 49, closeness: 0, owner_id: nil},
  {study_id: 48, replicating_study_id: 54, closeness: 0, owner_id: 3},
  {study_id: 55, replicating_study_id: 54, closeness: 0, owner_id: 4},
  {study_id: 55, replicating_study_id: 49, closeness: 0, owner_id: 4},
  {study_id: 50, replicating_study_id: 49, closeness: 0, owner_id: 4},
  {study_id: 52, replicating_study_id: 46, closeness: 0, owner_id: 4},
  {study_id: 64, replicating_study_id: 47, closeness: 0, owner_id: 4},
  {study_id: 68, replicating_study_id: 59, closeness: 0, owner_id: 4},
  {study_id: 57, replicating_study_id: 67, closeness: 0, owner_id: 4},
  {study_id: 57, replicating_study_id: 68, closeness: 0, owner_id: 4},
  {study_id: 84, replicating_study_id: 59, closeness: 0, owner_id: 4},
  {study_id: 28, replicating_study_id: 29, closeness: 0, owner_id: nil},
  {study_id: 64, replicating_study_id: 67, closeness: 0, owner_id: nil},
  {study_id: 101, replicating_study_id: 99, closeness: 0, owner_id: 4},
  {study_id: 101, replicating_study_id: 79, closeness: 0, owner_id: 4},
  {study_id: 105, replicating_study_id: 106, closeness: 0, owner_id: 4},
  {study_id: 120, replicating_study_id: 118, closeness: 0, owner_id: 4},
  {study_id: 120, replicating_study_id: 119, closeness: 0, owner_id: 4},
  {study_id: 125, replicating_study_id: 123, closeness: 0, owner_id: 4},
  {study_id: 125, replicating_study_id: 124, closeness: 0, owner_id: 4},
  {study_id: 66, replicating_study_id: 28, closeness: 0, owner_id: 3},
  {study_id: 140, replicating_study_id: 85, closeness: 0, owner_id: 3},
  {study_id: 140, replicating_study_id: 28, closeness: 0, owner_id: 3},
  {study_id: 140, replicating_study_id: 86, closeness: 0, owner_id: 3},
  {study_id: 171, replicating_study_id: 183, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 184, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 187, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 175, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 176, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 177, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 178, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 179, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 180, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 181, closeness: 0, owner_id: 4},
  {study_id: 171, replicating_study_id: 182, closeness: 0, owner_id: 4},
  {study_id: 197, replicating_study_id: 200, closeness: 0, owner_id: 4},
  {study_id: 197, replicating_study_id: 198, closeness: 0, owner_id: 4},
  {study_id: 210, replicating_study_id: 213, closeness: 0, owner_id: 4},
  {study_id: 212, replicating_study_id: 214, closeness: 0, owner_id: 4},
  {study_id: 125, replicating_study_id: 215, closeness: 0, owner_id: 4},
  {study_id: 219, replicating_study_id: 222, closeness: 0, owner_id: 4},
  {study_id: 219, replicating_study_id: 224, closeness: 0, owner_id: 4},
  {study_id: 220, replicating_study_id: 223, closeness: 0, owner_id: 4},
  {study_id: 220, replicating_study_id: 221, closeness: 0, owner_id: 4},
  {study_id: 225, replicating_study_id: 226, closeness: 0, owner_id: 4},
  {study_id: 229, replicating_study_id: 230, closeness: 0, owner_id: 4},
  {study_id: 229, replicating_study_id: 231, closeness: 0, owner_id: 4},
  {study_id: 241, replicating_study_id: 238, closeness: 0, owner_id: 2},
  {study_id: 129, replicating_study_id: 135, closeness: 0, owner_id: 4},
  {study_id: 129, replicating_study_id: 242, closeness: 0, owner_id: 4},
  {study_id: 129, replicating_study_id: 133, closeness: 0, owner_id: 4}
])
Study.create!([
  {n: 120, article_id: 228612, power: 0.99, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {"d"=>-0.07}, dependent_variables: [], independent_variables: []},
  {n: 120, article_id: 60041, power: 0.99, owner_id: nil, number: "Study 1", comment_count: 1, effect_size: {"d"=>-0.07}, dependent_variables: [], independent_variables: []},
  {n: 314, article_id: 93552, power: 0.99, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>0.19}, dependent_variables: [], independent_variables: []},
  {n: 49, article_id: 93558, power: nil, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>-0.83}, dependent_variables: [], independent_variables: ["Eye movement vs. control (between-subjects)"]},
  {n: nil, article_id: 93561, power: nil, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 48, article_id: 93561, power: nil, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {"d"=>0.63}, dependent_variables: [], independent_variables: ["Heat-related primes vs. neutral"]},
  {n: nil, article_id: 62641, power: nil, owner_id: 2, number: "1", comment_count: 0, effect_size: {}, dependent_variables: ["ANS Acuity", "Standardized Test Score"], independent_variables: []},
  {n: 50, article_id: 335169, power: 0.93, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {"d"=>0.21}, dependent_variables: [], independent_variables: []},
  {n: 25, article_id: 49183, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 50813, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 228612, power: nil, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 78, article_id: 93548, power: nil, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {"d"=>0.7}, dependent_variables: [], independent_variables: []},
  {n: 120, article_id: 93562, power: 0.93, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {"d"=>-0.12}, dependent_variables: [], independent_variables: ["Heat-related primes vs. neutral"]},
  {n: 27, article_id: 59287, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: ["Memory"], independent_variables: ["Cogn Load"]},
  {n: 27, article_id: 59287, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: ["Memory"], independent_variables: ["Distraction"]},
  {n: 27, article_id: 59288, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: ["DV2"], independent_variables: ["IV1"]},
  {n: 56, article_id: 60036, power: nil, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"d"=>-0.42}, dependent_variables: [], independent_variables: []},
  {n: 219, article_id: 60035, power: 0.98, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"d"=>0.022}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 59288, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: ["Desirability of cleaning-related products dddddddddddddddd"], independent_variables: ["Recalling ethical vs. unethical deed"]},
  {n: 27, article_id: 47406, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 40, article_id: 53406, power: nil, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"d"=>0.76}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 57128, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 57128, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 57128, power: 86.0, owner_id: nil, number: nil, comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 120, article_id: 57203, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 152, article_id: 93544, power: 0.99, owner_id: 4, number: "Study 2", comment_count: 3, effect_size: {"d"=>-0.14}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 93544, power: nil, owner_id: 4, number: "Study 3", comment_count: 1, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 30, article_id: 60040, power: nil, owner_id: nil, number: "Study 2b", comment_count: 0, effect_size: {"d"=>0.82}, dependent_variables: ["Walking speed"], independent_variables: ["Elderly priming (Scrambled sentence task)"]},
  {n: 66, article_id: 60042, power: 0.99, owner_id: nil, number: "", comment_count: 2, effect_size: {"d"=>-0.22}, dependent_variables: [], independent_variables: []},
  {n: 98, article_id: 93549, power: 0.93, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {"d"=>-0.24}, dependent_variables: [], independent_variables: []},
  {n: 31, article_id: 93556, power: 0.39, owner_id: 4, number: "Study 1", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 331, article_id: 93562, power: 0.99, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {"d"=>-0.06}, dependent_variables: [], independent_variables: ["Heat-related primes vs. neutral"]},
  {n: 71, article_id: 59309, power: nil, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"d"=>0.59}, dependent_variables: ["1/f noise on WIT"], independent_variables: ["Effort (Use/Avoid Race vs. Control)"]},
  {n: nil, article_id: 60034, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 59290, power: 86.0, owner_id: nil, number: "1a", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: ["you1"], independent_variables: ["you", "me"]},
  {n: 27, article_id: 56694, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 53678, power: nil, owner_id: nil, number: "1", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 53678, power: nil, owner_id: nil, number: "4", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 48, article_id: 93543, power: nil, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>1.21}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 52529, power: nil, owner_id: nil, number: "4", comment_count: 0, effect_size: {}, dependent_variables: ["shoulder"], independent_variables: ["hair"]},
  {n: nil, article_id: 60041, power: nil, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 53678, power: nil, owner_id: nil, number: "2a", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 51124, power: nil, owner_id: nil, number: "1", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 51124, power: nil, owner_id: nil, number: "2", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 51124, power: nil, owner_id: nil, number: "3", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 10, article_id: 52529, power: 0.1, owner_id: nil, number: "3", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 60033, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 82, article_id: 335170, power: 0.99, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>0.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 59293, power: 86.0, owner_id: nil, number: "study 1", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 356, article_id: 60047, power: 0.99, owner_id: nil, number: "", comment_count: 1, effect_size: {"r"=>-0.025}, dependent_variables: ["Physical warmth index"], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 49498, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: 27, article_id: 57132, power: 86.0, owner_id: nil, number: "", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 53678, power: nil, owner_id: nil, number: "3a", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 10, article_id: 52529, power: 0.1, owner_id: nil, number: "2", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 233, article_id: 60035, power: 0.99, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"d"=>0.031}, dependent_variables: [], independent_variables: []},
  {n: 66, article_id: 93549, power: nil, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {"d"=>-0.03}, dependent_variables: [], independent_variables: []},
  {n: 30, article_id: 59293, power: 0.6, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"d"=>1.08}, dependent_variables: [], independent_variables: ["Happy"]},
  {n: 148, article_id: 59297, power: 0.86, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"d"=>-0.09}, dependent_variables: ["1/f noise on WIT"], independent_variables: ["Effort (Use/Avoid Race vs. Control)"]},
  {n: 27, article_id: 52529, power: 0.86, owner_id: nil, number: "1", comment_count: 1, effect_size: {"d"=>1.08}, dependent_variables: ["dogs"], independent_variables: ["Cats", "Rabbits"]},
  {n: 148, article_id: 59297, power: 0.86, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"d"=>0.16}, dependent_variables: ["1/f noise on WIT"], independent_variables: ["Effort (Use/Avoid Race vs. Control)"]},
  {n: 240, article_id: 60039, power: 0.99, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"d"=>0.18}, dependent_variables: [], independent_variables: []},
  {n: 90, article_id: 60039, power: 0.99, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"d"=>-0.32}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 54201, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 57040, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: nil, article_id: 53764, power: nil, owner_id: nil, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 365, article_id: 60046, power: 0.99, owner_id: nil, number: "", comment_count: 0, effect_size: {"r"=>-0.03}, dependent_variables: ["Physical warmth index"], independent_variables: []},
  {n: 51, article_id: 49900, power: nil, owner_id: nil, number: "Study 1a", comment_count: 0, effect_size: {"r"=>0.57}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: 553, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 6", comment_count: 0, effect_size: {"r"=>0.06}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: 311, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 7", comment_count: 0, effect_size: {"r"=>0.02}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: 365, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 8", comment_count: 0, effect_size: {"r"=>0.02}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: nil, article_id: 93548, power: nil, owner_id: 4, number: "Study 3", comment_count: 1, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 40, article_id: 93553, power: nil, owner_id: 4, number: "Study 4", comment_count: 0, effect_size: {"d"=>0.9}, dependent_variables: [], independent_variables: []},
  {n: 147, article_id: 93544, power: 0.99, owner_id: 4, number: "Study 1", comment_count: 1, effect_size: {"d"=>0.18}, dependent_variables: [], independent_variables: []},
  {n: 24, article_id: 59309, power: nil, owner_id: nil, number: " Study 1", comment_count: 0, effect_size: {"r"=>0.24}, dependent_variables: ["1/f noise on WIT"], independent_variables: [" "]},
  {n: 30, article_id: 60040, power: nil, owner_id: nil, number: "Study 2a", comment_count: 1, effect_size: {"d"=>1.08}, dependent_variables: ["Walking speed"], independent_variables: ["Elderly priming (Scrambled sentence task)"]},
  {n: 50, article_id: 93553, power: nil, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {"d"=>0.62}, dependent_variables: [], independent_variables: []},
  {n: 197, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 9", comment_count: 0, effect_size: {"r"=>-0.13}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: 41, article_id: 49900, power: nil, owner_id: nil, number: "Study 1b", comment_count: 0, effect_size: {"r"=>0.37}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]},
  {n: 60, article_id: 93555, power: 0.66, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>0.26}, dependent_variables: [], independent_variables: []},
  {n: 31, article_id: 93556, power: 0.68, owner_id: 4, number: "Study 2", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 14, article_id: 93557, power: nil, owner_id: 4, number: "", comment_count: 0, effect_size: {"d"=>0.51}, dependent_variables: [], independent_variables: ["Eye movement vs. control (within-subjects)"]},
  {n: 480, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 2", comment_count: 0, effect_size: {"r"=>-0.01}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (20-item UCLA scale version 3)"]},
  {n: 235, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 1", comment_count: 0, effect_size: {"r"=>-0.06}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (20-item UCLA scale version 3)"]},
  {n: 41, article_id: 93554, power: 0.8, owner_id: 4, number: "", comment_count: 0, effect_size: {}, dependent_variables: [], independent_variables: []},
  {n: 210, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 3", comment_count: 0, effect_size: {"r"=>0.13}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (20-item UCLA scale version 3)"]},
  {n: 228, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 4", comment_count: 0, effect_size: {"r"=>-0.1}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (20-item UCLA scale version 3)"]},
  {n: 494, article_id: 60045, power: 0.98, owner_id: nil, number: "Study 5", comment_count: 0, effect_size: {"r"=>0.1}, dependent_variables: ["Physical warmth index"], independent_variables: ["Trait loneliness (10-item version of UCLA scale)"]}
])
Article.create!([
  {doi: "10.1186/1749-8104-5-8", title: "Cortico-cerebral histogenesis in the opossum Monodelphis domestica: generation of a hexalaminar neocortex in the absence of a basal proliferative compartment.", publication_date: "2010-01-01", abstract: "The metatherian Monodelphis domestica, commonly known as the South-American short-tailed opossum, is an appealing animal model for developmental studies on cortico-cerebral development. Given its phylogenetic position, it can help in tracing evolutionary origins of key traits peculiar to the eutherian central nervous system. The capability of its pup to regenerate damaged cortico-spinal connections makes it an ideal substrate for regenerative studies. Recent sequencing of its genome and the ex utero accessibility of its developing cerebral cortex further enhance its experimental interest. However, at the moment, a comprehensive cellular and molecular characterization of its cortical development is missing.A systematic analysis of opossum cortico-cerebral development was performed, including: origin of cortical neurons; migration of these neurons from their birthplaces to their final layer destinations; and molecular differentiation of distinct neocortical laminae. We observed that opossum projection neurons and interneurons are generated by pallial and subpallial precursors, respectively, similar to rodents. A six-layered cortex with a eutherian-like molecular profile is laid down, according to the inside-out rule. However, neocortical projection neurons are generated by apical neural precursors and almost no basal progenitors may be found in the neuronogenic neopallial primordium. In the opossum neocortex, Tbr2, the hallmark of eutherian basal progenitors, is transiently expressed by postmitotic progenies of apical precursors prior to the activation of more mature neuronal markers.The neocortical developmental program predates Eutheria-Methatheria branching. However, in metatherians, unlike eutherians, a basal proliferative compartment is not needed for the formation of a six-layered neuronal blueprint.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Elisa", :middle_name=>nil, :last_name=>"Puzzolo"}, {:first_name=>"Antonello", :middle_name=>nil, :last_name=>"Mallamaci"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1186/1749-8104-5-7", title: "Insulin receptor signaling in the development of neuronal structure and function.", publication_date: "2010-01-01", abstract: "Sensory experience plays a crucial role in regulating neuronal shape and in developing synaptic contacts during brain formation. These features are required for a neuron to receive, integrate, and transmit signals within the neuronal network so that animals can adapt to the constant changing environment. Insulin receptor signaling, which has been extensively studied in peripheral organ systems such as liver, muscle and adipocyte, has recently been shown to play important roles in the central nervous system. Here we review the current understanding of the underlying mechanisms that regulate structural and functional aspects of circuit development, particularly with respect to the role of insulin receptor signaling in synaptic function and the development of dendritic arbor morphology. The potential link between insulin receptor signaling malfunction and neurological disorders will also be discussed.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Shu-Ling", :middle_name=>nil, :last_name=>"Chiu"}, {:first_name=>"Hollis T", :middle_name=>nil, :last_name=>"Cline"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1371/journal.pone.0009695", title: "FaaPred: a SVM-based prediction method for fungal adhesins and adhesin-like proteins.", publication_date: "2010-01-01", abstract: "Adhesion constitutes one of the initial stages of infection in microbial diseases and is mediated by adhesins. Hence, identification and comprehensive knowledge of adhesins and adhesin-like proteins is essential to understand adhesin mediated pathogenesis and how to exploit its therapeutic potential. However, the knowledge about fungal adhesins is rudimentary compared to that of bacterial adhesins. In addition to host cell attachment and mating, the fungal adhesins play a significant role in homotypic and xenotypic aggregation, foraging and biofilm formation. Experimental identification of fungal adhesins is labor- as well as time-intensive. In this work, we present a Support Vector Machine (SVM) based method for the prediction of fungal adhesins and adhesin-like proteins. The SVM models were trained with different compositional features, namely, amino acid, dipeptide, multiplet fractions, charge and hydrophobic compositions, as well as PSI-BLAST derived PSSM matrices. The best classifiers are based on compositional properties as well as PSSM and yield an overall accuracy of 86%. The prediction method based on best classifiers is freely accessible as a world wide web based server at http://bioinfo.icgeb.res.in/faap. This work will aid rapid and rational identification of fungal adhesins, expedite the pace of experimental characterization of novel fungal adhesins and enhance our knowledge about role of adhesins in fungal infections.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Jayashree", :middle_name=>nil, :last_name=>"Ramana"}, {:first_name=>"Dinesh", :middle_name=>nil, :last_name=>"Gupta"}], owner_id: nil, comment_count: 0, journal_title: "PloS one", journal_issn: "1932-6203", tags: nil},
  {doi: "10.1186/1749-8104-4-5", title: "Ascl1 is a required downstream effector of Gsx gene function in the embryonic mouse telencephalon.", publication_date: "2009-01-01", abstract: "The homeobox gene Gsx2 (formerly Gsh2) is known to regulate patterning in the lateral ganglionic eminence (LGE) of the embryonic telencephalon. In its absence, the closely related gene Gsx1 (previously known as Gsh1) can partially compensate in the patterning and differentiation of ventral telencephalic structures, such as the striatum. However, the cellular and molecular mechanisms underlying this compensation remain unclear.We show here that in the Gsx2 mutants Gsx1 is expressed in only a subset of the ventral telencephalic progenitors that normally express Gsx2. Based on the similarities in the expression of Gsx1 and Ascl1 (Mash1) within the Gsx2 mutant LGE, we examined whether Ascl1 plays an integral part in the Gsx1-based recovery. Ascl1 mutants show only modest alterations in striatal development; however, in Gsx2;Ascl1 double mutants, striatal development is severely affected, similar to that seen in the Gsx1;Gsx2 double mutants. This is despite the fact that Gsx1 is expressed, and even expands, in the Gsx2;Ascl1 mutant LGE, comparable to that seen in the Gsx2 mutant. Finally, Notch signaling has recently been suggested to be required for normal striatal development. In spite of the fact that Notch signaling is severely disrupted in Ascl1 mutants, it actually appears to be improved in the Gsx2;Ascl1 double mutants.These results, therefore, reveal a non-proneural requirement of Ascl1 that together with Gsx1 compensates for the loss of Gsx2 in a subset of LGE progenitors.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Bei", :middle_name=>nil, :last_name=>"Wang"}, {:first_name=>"Ronald R", :middle_name=>nil, :last_name=>"Waclaw"}, {:first_name=>"Zegary J", :middle_name=>nil, :last_name=>"Allen"}, {:first_name=>"Francois", :middle_name=>nil, :last_name=>"Guillemot"}, {:first_name=>"Kenneth", :middle_name=>nil, :last_name=>"Campbell"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1016/j.neunet.2008.09.011", title: "A novel approach to neuro-fuzzy classification.", publication_date: "2009-01-01", abstract: "A new model for neuro-fuzzy (NF) classification systems is proposed. The motivation is to utilize the feature-wise degree of belonging of patterns to all classes that are obtained through a fuzzification process. A fuzzification process generates a membership matrix having total number of elements equal to the product of the number of features and classes present in the data set. These matrix elements are the input to neural networks. The effectiveness of the proposed model is established with four benchmark data sets (completely labeled) and two remote sensing images (partially labeled). Different performance measures such as misclassification, classification accuracy and kappa index of agreement for completely labeled data sets, and beta index of homogeneity and Davies-Bouldin (DB) index of compactness for remotely sensed images are used for quantitative analysis of results. All these measures supported the superiority of the proposed NF classification model. The proposed model learns well even with a lower percentage of training data that makes the system fast.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Ashish", :middle_name=>nil, :last_name=>"Ghosh"}, {:first_name=>"B Uma", :middle_name=>nil, :last_name=>"Shankar"}, {:first_name=>"Saroj K", :middle_name=>nil, :last_name=>"Meher"}], owner_id: nil, comment_count: 0, journal_title: "Neural networks : the official journal of the International Neural Network Society", journal_issn: "0893-6080", tags: nil},
  {doi: "10.1186/1749-8104-4-4", title: "Fgf receptor 3 activation promotes selective growth and expansion of occipitotemporal cortex.", publication_date: "2009-01-01", abstract: "Fibroblast growth factors (Fgfs) are important regulators of cerebral cortex development. Fgf2, Fgf8 and Fgf17 promote growth and specification of rostromedial (frontoparietal) cortical areas. Recently, the function of Fgf15 in antagonizing Fgf8 in the rostral signaling center was also reported. However, regulation of caudal area formation by Fgf signaling remains unknown.In mutant mice with constitutive activation of Fgf receptor 3 (Fgfr3) in the forebrain, surface area of the caudolateral cortex was markedly expanded at early postnatal stage, while rostromedial surface area remained normal. Cortical thickness was also increased in caudal regions. The expression domain and levels of Fgf8, as well as overall patterning, were unchanged. In contrast, the changes in caudolateral surface area were associated with accelerated cell cycle in early stages of neurogenesis without an alteration of cell cycle exit. Moreover, a marked overproduction of intermediate neuronal progenitors was observed in later stages, indicating prolongation of neurogenesis.Activation of Fgfr3 selectively promotes growth of caudolateral (occipitotemporal) cortex. These observations support the 'radial unit' and 'radial amplification' hypotheses and may explain premature sulcation of the occipitotemporal cortex in thanatophoric dysplasia, a human FGFR3 disorder. Together with previous work, this study suggests that formation of rostral and caudal areas are differentially regulated by Fgf signaling in the cerebral cortex.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Rachel E", :middle_name=>nil, :last_name=>"Thomson"}, {:first_name=>"Peter C", :middle_name=>nil, :last_name=>"Kind"}, {:first_name=>"Nicholas A", :middle_name=>nil, :last_name=>"Graham"}, {:first_name=>"Michelle L", :middle_name=>nil, :last_name=>"Etherson"}, {:first_name=>"John", :middle_name=>nil, :last_name=>"Kennedy"}, {:first_name=>"Ana C", :middle_name=>nil, :last_name=>"Fernandes"}, {:first_name=>"Catia S", :middle_name=>nil, :last_name=>"Marques"}, {:first_name=>"Robert F", :middle_name=>nil, :last_name=>"Hevner"}, {:first_name=>"Tomoko", :middle_name=>nil, :last_name=>"Iwata"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1371/journal.pone.0009218", title: "In vitro fertilization and embryo culture strongly impact the placental transcriptome in the mouse model.", publication_date: "2010-01-01", abstract: "Assisted Reproductive Technologies (ART) are increasingly used in humans; however, their impact is now questioned. At blastocyst stage, the trophectoderm is directly in contact with an artificial medium environment, which can impact placental development. This study was designed to carry out an in-depth analysis of the placental transcriptome after ART in mice.Blastocysts were transferred either (1) after in vivo fertilization and development (control group) or (2) after in vitro fertilization and embryo culture. Placentas were then analyzed at E10.5. Six percent of transcripts were altered at the two-fold threshold in placentas of manipulated embryos, 2/3 of transcripts being down-regulated. Strikingly, the X-chromosome harbors 11% of altered genes, 2/3 being induced. Imprinted genes were modified similarly to the X. Promoter composition analysis indicates that FOXA transcription factors may be involved in the transcriptional deregulations.For the first time, our study shows that in vitro fertilization associated with embryo culture strongly modify the placental expression profile, long after embryo manipulations, meaning that the stress of artificial environment is memorized after implantation. Expression of X and imprinted genes is also greatly modulated probably to adapt to adverse conditions. Our results highlight the importance of studying human placentas from ART.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Patricia", :middle_name=>nil, :last_name=>"Fauque"}, {:first_name=>"Françoise", :middle_name=>nil, :last_name=>"Mondon"}, {:first_name=>"Franck", :middle_name=>nil, :last_name=>"Letourneur"}, {:first_name=>"Marie-Anne", :middle_name=>nil, :last_name=>"Ripoche"}, {:first_name=>"Laurent", :middle_name=>nil, :last_name=>"Journot"}, {:first_name=>"Sandrine", :middle_name=>nil, :last_name=>"Barbaux"}, {:first_name=>"Luisa", :middle_name=>nil, :last_name=>"Dandolo"}, {:first_name=>"Catherine", :middle_name=>nil, :last_name=>"Patrat"}, {:first_name=>"Jean-Philippe", :middle_name=>nil, :last_name=>"Wolf"}, {:first_name=>"Pierre", :middle_name=>nil, :last_name=>"Jouannet"}, {:first_name=>"Hélène", :middle_name=>nil, :last_name=>"Jammes"}, {:first_name=>"Daniel", :middle_name=>nil, :last_name=>"Vaiman"}], owner_id: nil, comment_count: 0, journal_title: "PloS one", journal_issn: "1932-6203", tags: nil},
  {doi: "10.1186/1749-8104-4-3", title: "Adenomatous polyposis coli is required for early events in the normal growth and differentiation of the developing cerebral cortex.", publication_date: "2009-01-01", abstract: "Adenomatous polyposis coli (Apc) is a large multifunctional protein known to be important for Wnt/beta-catenin signalling, cytoskeletal dynamics, and cell polarity. In the developing cerebral cortex, Apc is expressed in proliferating cells and its expression increases as cells migrate to the cortical plate. We examined the consequences of loss of Apc function for the early development of the cerebral cortex.We used Emx1(Cre) to inactivate Apc specifically in proliferating cerebral cortical cells and their descendents starting from embryonic day 9.5. We observed reduction in the size of the mutant cerebral cortex, disruption to its organisation, and changes in the molecular identity of its cells. Loss of Apc leads to a decrease in the size of the proliferative pool, disrupted interkinetic nuclear migration, and increased apoptosis. beta-Catenin, pericentrin, and N-cadherin proteins no longer adopt their normal high concentration at the apical surface of the cerebral cortical ventricular zone, indicating that cell polarity is disrupted. Consistent with enhanced Wnt/beta-catenin signalling resulting from loss of Apc we found increased levels of TCF/LEF-dependent transcription and expression of endogenous Wnt/beta-catenin target genes (Axin2 (conductin), Lef1, and c-myc) in the mutant cerebral cortex. In the Apc mutant cerebral cortex the expression of transcription factors Foxg1, Pax6, Tbr1, and Tbr2 is drastically reduced compared to normal and many cells ectopically express Pax3, Wnt1, and Wt1 (but not Wnt2b, Wnt8b, Ptc, Gli1, Mash1, Olig2, or Islet1). This indicates that loss of Apc function causes cerebral cortical cells to lose their normal identity and redirect to fates normally found in more posterior-dorsal regions of the central nervous system.Apc is required for multiple aspects of early cerebral cortical development, including the regulation of cell number, interkinetic nuclear migration, cell polarity, and cell type specification.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Uladzislau", :middle_name=>nil, :last_name=>"Ivaniutsin"}, {:first_name=>"Yijing", :middle_name=>nil, :last_name=>"Chen"}, {:first_name=>"John O", :middle_name=>nil, :last_name=>"Mason"}, {:first_name=>"David J", :middle_name=>nil, :last_name=>"Price"}, {:first_name=>"Thomas", :middle_name=>nil, :last_name=>"Pratt"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1186/1749-8104-4-2", title: "Heterogeneity in the developmental potential of motor neuron progenitors revealed by clonal analysis of single cells in vitro.", publication_date: "2009-01-01", abstract: "The differentiation of neural progenitors into distinct classes within the central nervous system occurs over an extended period during which cells become progressively restricted in their fates. In the developing spinal cord, Sonic Hedgehog (Shh) controls neural fates in a concentration-dependent manner by establishing discrete ventral progenitor domains characterized by specific combinations of transcription factors. It is unclear whether motor neuron progenitors can maintain their identities when expanded in vitro and whether their developmental potentials are restricted when exposed to defined extracellular signals.We have generated mice expressing the enhanced green fluorescent protein under the control of the Nkx6.1 promoter, enabling fluorescence-activated cell sorting (FACS), purification and culture of individual spinal progenitors at clonal density, and analysis of their progeny. We demonstrate that cells isolated after progenitor domains are established are heterogeneous with respect to maintaining their identity after in vitro expansion. Most Nkx6.1+ progenitors lose their ventral identity following several divisions in culture, whereas a small subset is able to maintain its identity. Thus, subtype-restricted progenitors from the Nkx6.1+ region are present in the ventral spinal cord, although at a lower frequency than expected. Clones that maintain a motor neuron identity assume a transcriptional profile characteristic of thoracic motor neurons, despite some having been isolated from non-thoracic regions initially. Exposure of progenitors to Bone Morphogenetic Protein-4 induces some dorsal cell type characteristics in their progeny, revealing that lineage-restricted progenitor subtypes are not fully committed to their fates.These findings support a model whereby continuous Shh signaling is required to maintain the identity of ventral progenitors isolated from the spinal cord, including motor neuron progenitors, after in vitro expansion. They also demonstrate that pre-patterned neural progenitors isolated from the central nervous system can change their regional identity in vitro to acquire a broader developmental potential.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Dritan", :middle_name=>nil, :last_name=>"Agalliu"}, {:first_name=>"Ira", :middle_name=>nil, :last_name=>"Schieren"}], owner_id: nil, comment_count: 0, journal_title: "Neural development", journal_issn: "1749-8104", tags: nil},
  {doi: "10.1371/journal.pone.0009694", title: "Morbid obesity as a risk factor for hospitalization and death due to 2009 pandemic influenza A(H1N1) disease.", publication_date: "2010-01-01", abstract: "Severe illness due to 2009 pandemic A(H1N1) infection has been reported among persons who are obese or morbidly obese. We assessed whether obesity is a risk factor for hospitalization and death due to 2009 pandemic influenza A(H1N1), independent of chronic medical conditions considered by the Advisory Committee on Immunization Practices (ACIP) to increase the risk of influenza-related complications.We used a case-cohort design to compare cases of hospitalizations and deaths from 2009 pandemic A(H1N1) influenza occurring between April-July, 2009, with a cohort of the U.S. population estimated from the 2003-2006 National Health and Nutrition Examination Survey (NHANES); pregnant women and children <2 years old were excluded. For hospitalizations, we defined categories of relative weight by body mass index (BMI, kg/m(2)); for deaths, obesity or morbid obesity was recorded on medical charts, and death certificates. Odds ratio (OR) of being in each BMI category was determined; normal weight was the reference category. Overall, 361 hospitalizations and 233 deaths included information to determine BMI category and presence of ACIP-recognized medical conditions. Among >or=20 year olds, hospitalization was associated with being morbidly obese (BMI>or=40) for individuals with ACIP-recognized chronic conditions (OR = 4.9, 95% CI 2.4-9.9) and without ACIP-recognized chronic conditions (OR = 4.7, 95%CI 1.3-17.2). Among 2-19 year olds, hospitalization was associated with being underweight (BMI<or=5(th) percentile) among those with (OR = 12.5, 95%CI 3.4-45.5) and without (OR = 5.5, 95%CI 1.3-22.5) ACIP-recognized chronic conditions. Death was not associated with BMI category among individuals 2-19 years old. Among individuals aged >or=20 years without ACIP-recognized chronic medical conditions death was associated with obesity (OR = 3.1, 95%CI: 1.5-6.6) and morbid obesity (OR = 7.6, 95%CI 2.1-27.9).Our findings support observations that morbid obesity may be associated with hospitalization and possibly death due to 2009 pandemic H1N1 infection. These complications could be prevented by early antiviral therapy and vaccination.", repeatability: 0.0, materials: 0.0, quality_of_stats: 0.0, disclosure: 0.0, authors_denormalized: [{:first_name=>"Oliver W", :middle_name=>nil, :last_name=>"Morgan"}, {:first_name=>"Anna", :middle_name=>nil, :last_name=>"Bramley"}, {:first_name=>"Ashley", :middle_name=>nil, :last_name=>"Fowlkes"}, {:first_name=>"David S", :middle_name=>nil, :last_name=>"Freedman"}, {:first_name=>"Thomas H", :middle_name=>nil, :last_name=>"Taylor"}, {:first_name=>"Paul", :middle_name=>nil, :last_name=>"Gargiullo"}, {:first_name=>"Brook", :middle_name=>nil, :last_name=>"Belay"}, {:first_name=>"Seema", :middle_name=>nil, :last_name=>"Jain"}, {:first_name=>"Chad", :middle_name=>nil, :last_name=>"Cox"}, {:first_name=>"Laurie", :middle_name=>nil, :last_name=>"Kamimoto"}, {:first_name=>"Anthony", :middle_name=>nil, :last_name=>"Fiore"}, {:first_name=>"Lyn", :middle_name=>nil, :last_name=>"Finelli"}, {:first_name=>"Sonja J", :middle_name=>nil, :last_name=>"Olsen"}, {:first_name=>"Alicia M", :middle_name=>nil, :last_name=>"Fry"}], owner_id: nil, comment_count: 0, journal_title: "PloS one", journal_issn: "1932-6203", tags: nil}
])
